version: "3"
services:
  backend:
    build:
      context: ./delivery-nest
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db 
    command: npm run start
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=delivery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111